### ISSUE TITLE
Data Ingestion - Household income

### ISSUE THREAD

**Issue by mayaspivak** [SatcherInstitute/prototype#14]
Create a scheduler job to get household income data into GCS bucket

https://data.ers.usda.gov/reports.aspx?ID=17828

**Comment by jenniebrown** [comment]
Added a cloud scheduler job to run every Thursday in the test project called household-income-scheduler. According to the USDA website, this data is only updated once per year. Running once per week will help catch issues if the data source is moved, for example.

**Comment by slagathorr** [comment]
Can you point me to where this schedule is? I'm starting to put together the Terraform scripts and it would make sense to include this.

**Comment by jenniebrown** [comment]
Sure, it's in the fellowship-test-internal project named household-income-scheduler. I added it through the UI so I don't have any configuration elsewhere.

**Comment by mayaspivak** [comment]
This issue will now also include a function/service to get the data from GCS into bigquery and any data standardization that needs to be done within bigquery.
