### ISSUE TITLE
Data Ingestion - Urgent care

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/prototype#20]
Create a scheduler job to get num urgent care facilities into GCS bucket

Urgent care: https://hifld-geoplatform.opendata.arcgis.com/datasets/urgent-care-facilities/data
Possibly https://catalog.data.gov/dataset/urgent-care-facilities

Lorenzo- not sure how these datasets differ

**Comment by mayaspivak** [comment]
This issue will now also include a function/service to get the data from GCS into bigquery and any data standardization that needs to be done within bigquery.

**Comment by ldbnr4** [comment]
Maya - thanks for the update

Krista -  it looks like they are the same, the second "source" seems to just acknowledge that the first source exists

**Comment by ldbnr4** [comment]
Cloud function deployed. We'll need to discuss how to structure our code base to have this checked in.
