### ISSUE TITLE
Data Ingestion - Primary care physician access

### ISSUE THREAD

**Issue by mayaspivak** [SatcherInstitute/prototype#6]
Create a scheduler job to get num primary care physicians into GCS bucket

Primary care physician: https://www.countyhealthrankings.org/explore-health-rankings/measures-data-sources/county-health-rankings-model/health-factors/clinical-care/access-to-care/primary-care-physicians

**Comment by mayaspivak** [comment]
This issue will now also include a function/service to get the data from GCS into bigquery and any data standardization that needs to be done within bigquery.

**Comment by kkatzen** [comment]
Oops ignore that i linked the wrong PR. PR #41 resolved this. Closing now!
